# Generated by Django 2.2.2 on 2019-07-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20190702_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('email_content', models.TextField(blank=True, null=True)),
                ('is_send', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('start_time',)},
        ),
    ]
